#!/bin/bash
# Set Wallpaper & Persist across Reboots

IMG="$1"
[ -z "$IMG" ] || [ ! -f "$IMG" ] && { notify-send "Error" "No valid image file provided"; exit 1; }

IMG_PATH="$(realpath "$IMG")"
mkdir -p ~/.cache ~/.local/state/caelestia/wallpaper
echo "$IMG_PATH" > ~/.cache/current_wallpaper
echo "$IMG_PATH" > ~/.local/state/caelestia/wallpaper/path.txt
caelestia wallpaper -f "$IMG_PATH"
notify-send -i "$IMG_PATH" "Caelestia" "Wallpaper set & saved!"
